<?php
if( function_exists('acf_add_local_field_group') ):

  acf_add_local_field_group(array(
    'key' => 'group_61658832e6c3e',
    'title' => 'Restrição por CEP',
    'fields' => array(
      array(
        'key' => 'field_61658e836863f',
        'label' => 'Faixas de CEP',
        'name' => 'faixas_de_cep',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => 'Adicionar faixa de CEP',
        'sub_fields' => array(
          array(
            'key' => 'field_61658e8368640',
            'label' => 'De',
            'name' => 'de',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'somente números',
            'prepend' => '',
            'append' => '',
            'maxlength' => 9,
          ),
          array(
            'key' => 'field_61658fb71d857',
            'label' => 'Até',
            'name' => 'ate',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => 'somente números',
            'prepend' => '',
            'append' => '',
            'maxlength' => 9,
          ),
        ),
      ),
      array(
        'key' => 'field_6165b1096ddc9',
        'label' => 'CEPs específicos',
        'name' => 'ceps_especificos',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => 'Adicionar CEP',
        'sub_fields' => array(
          array(
            'key' => 'field_6165b11a6ddca',
            'label' => 'CEP',
            'name' => 'cep',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '',
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => 9,
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'product',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));
  
  endif;